### ISSUE TITLE
bot spamming: dotnet-help command triggers multiple comments

### ISSUE THREAD

**Issue by am11** [dotnet/dotnet-ci#1087]
In downstream repos' PRs, the help command is getting triggered multiple times for a single request. Sometimes bot posts a comment with help text when we issue subsequent command:

![image](https://user-images.githubusercontent.com/3840695/50591564-106ee900-0e99-11e9-931b-1f6bf457cca4.png)

and other times, the bot does that consecutively twice, then again after the subsequent command:

![image](https://user-images.githubusercontent.com/3840695/50591645-66439100-0e99-11e9-8f53-410f2d389bd6.png)

**Comment by mmitche** [comment]
The comments are actually coming from different servers.  They have no way to aggregate.
