### ISSUE TITLE
CoreCLR builds for Windows on ARM

### ISSUE THREAD

**Issue by kika123** [dotnet/dotnet-ci#140]
Windows on ARM builds should be included as they work well when compiled in my machine. Why aren't they tested by the bot?

**Comment by gkhanna79** [comment]
> work well when compiled in my machine.

Can you please elaborate on it? they are built in the CI and not locally. Which toolset are you using to compile locally?

> Why aren't they tested by the bot?

This is in works.

**Comment by kika123** [comment]
The CI  doesn't build it at all actually. I build myself using VS2015, to then use it on Windows 8.1 for ARM or a  MinWin Windows 10 build.(MSBuild actually works and compiles on 8.1 for ARM, as that has the legacy CSC.exe)

**Comment by kika123** [comment]
Also note that I use the legacy JIT :-)

**Comment by jashook** [comment]
Just to make sure you are referring to arm32 not arm64.

**Comment by kika123** [comment]
@jashook Yeah, I'm talking about arm32

**Comment by kika123** [comment]
Why?
