### ISSUE TITLE
Sync time across machines to time server

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/dotnet-ci#177]
Currently, machines across the dotnet-ci environment can be a few minutes ahead or behind others. As we start implementing cross-machine tests with security (e.g., SSL / Kerberos), significant time skews may cause issues with these tests. 

Consider running an NTP client to get time to be consistent across machines - i.e., no more than a few seconds of drift either way.

**Comment by mmitche** [comment]
@iamjasonp Is this typically run as a daemon on Linux or run on-demand?

**Comment by iamjasonp** [comment]
You can use `ntpdate` to adjust time on demand, or install `ntpd` (`sudo apt-get install ntp`) for continuous correction. Note however that installing ntpd will cause a server to be opened up on the machine too so others can sync time from it - not necessarily desired behaviour. 

Using (say) `ntpdate 0.pool.ntp.org` as a cron job works (I think it's already on-box by default on ubuntu and other distros) but will probably result in more drift compared to ntpd. That said, this drift should be well within our tolerance if we run ntpdate even weekly. Note that ntpdate needs superuser privileges to set the system time. 

I personally use ntpd on my box to keep time on my linux boxes because I'm lazy and don't really care about any incoming ntp connections. 

Using the cron job, be sure to edit the sudoers file to allow sudo without password for `ntpdate` for whichever user's you use to run the time sync.
