### ISSUE TITLE
FreeBSD CI-builds are failing

### ISSUE THREAD

**Issue by josteink** [dotnet/dotnet-ci#20]
As can be seen on via Jenkins: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_debug/

Looking into the first failing build, we have [this log](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_debug/4/console):

````
Cloning the remote Git repository
Cloning repository git://github.com/dotnet/coreclr.git
 > git init /mnt/tmpdrive/j/workspace/dotnet_coreclr_freebsd_debug # timeout=10
ERROR: Error cloning remote repo 'origin'
ERROR: Error cloning remote repo 'origin'
````

Failure to clone the repository could hint at the disks being full. But subsequent builds are failing for other reasons. That latest build gets to 16%, then suddenly Jenkins seems to disconnect and call it a day, so obviously something else is going on too.

@mmitche Looking at the [build log](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_debug/) It seem's you're already on this? :)

**Comment by mmitche** [comment]
Yeah I was looking at this yesterday.  I went to go create a new node, so I captured the old one and created two new versions.  Either it wasn't really working that well before and we just got lucky, or something happened in the deprovisioning and capture, because the temporary drive stopped working within a few minutes.and started giving IO errors.

**Comment by mmitche** [comment]
I've updated to the latest version of waagent, which has correct provisioning for the temporary disk.  Should be up and running quite soon.

**Comment by josteink** [comment]
Looking at the latest build they still don't seem entirely stable:

* http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_release/
* http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_debug/

Odd that they would chug along nicely to begin with and then suddenly stop working...

**Comment by mmitche** [comment]
@josteink I think we might actually be good here.  The last few failures on the 30th were real failures, but @ajensenwaud fixed this last night.  Woohoo!

**Comment by josteink** [comment]
Ooh right. Nice of him then :)

**Comment by mmitche** [comment]
Actually looks like you're right about the debug one.  It appears that for whatever reason, it didn't update it's workspace directory when I updated the value in Jenkins.  It was still using the primary drive, which has very little space.  I'll figure out what's going on.

**Comment by josteink** [comment]
Done any changes since last time? They're all looking good now. Feel free to close this issue at your own discretion.

**Comment by mmitche** [comment]
We are all good now, and the build will fail on FreeBSD failures now!

**Comment by jasonwilliams200OK** [comment]
@mmitche, @josteink, now that https://github.com/dotnet/coreclr/issues/1030 is merged, should the tests enabled for FreeBSD as well?

Related: https://github.com/dotnet/coreclr/issues/1010.

**Comment by mmitche** [comment]
@jasonwilliams200OK Yep will do so today

**Comment by josteink** [comment]
Currently 4 of the tests *are* failing. Will enabling the tests on the CI-build cause all PRs from now to turn red until we get those fixed?

If so I would advice to delay enabling the tests until we have the 4 failing tests fixed. 

(My 2 norwegian øre)

**Comment by mmitche** [comment]
@josteink Yes.  we should have them all passing before we enable them in the CI

**Comment by jasonwilliams200OK** [comment]
:+1: 
@joshfree, US :moneybag: for you! :wink:

**Comment by josteink** [comment]
@mmitche I looked slightly deeper into this, and it may be that enabling tests are safeish.

Can you take a look at the findings and weight in your opinion?

https://github.com/dotnet/coreclr/issues/1010#issuecomment-104756763

**Comment by mmitche** [comment]
@josteink I got two failures on an exploratory run:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_debug/lastFailedBuild/console

The following test(s) failed:
threading/WaitForSingleObject/WFSOExMutexTest/paltest_waitforsingleobject_wfsoexmutextest. Exit code: 1
threading/WaitForSingleObject/WFSOExThreadTest/paltest_waitforsingleobject_wfsoexthreadtest. Exit code: 1

PAL Test Results:
  Passed: 819
  Failed: 2

**Comment by josteink** [comment]
Ok. If so I still advice against enabling them. Was worth a shot though. :)

**Comment by jasonwilliams200OK** [comment]
How about we exclude these two tests for FreeBSD target something what these guys have done: https://github.com/dotnet/llilc/pull/598? I mean only 0.2% of tests are failing. I think it is a bad idea to hold back the majority.

**Comment by josteink** [comment]
Currently we're investigating the cause for those performing badly in #1044, but if those investigations turn up inconclusive or without any resolution, I'm inclined to agree with @jasonwilliams200OK .

**Comment by mmitche** [comment]
@jasonwilliams200OK Yeah that seems reasonable.  If it seems like the values in the tests are unreasonable (they were probably chosen somewhat arbitrarily in the ancient past) then we could also alter them.

**Comment by jasonwilliams200OK** [comment]
@mmitche, :+1: 

A very valuable and yet interesting discussion on this subject is going on here https://github.com/dotnet/coreclr/issues/1044 between @josteink and @bsdjhb (FreeBSD kernel dev). It seems like there is more to just the timer values which need adjustment. Hopefully, the root issue will be identified soon.
