### ISSUE TITLE
Jenkins Images with Git 2.9 or later need to disable the windows credential manager

### ISSUE THREAD

**Issue by tannergooding** [dotnet/dotnet-ci#358]
Git 2.9 or later enables the Windows Credential Manager by default

This adds the following lines to the `C:\Program Files\Git\mingw64\etc\gitconfig` file:

```
[credential]
    helper = manager
```

This causes internal repo's to popup a password dialog any time a new enlistment is needed.

**Comment by mmitche** [comment]
Thanks
