### ISSUE TITLE
The coreclr CI-build for FreeBSD should have PAL-tests enabled.

### ISSUE THREAD

**Issue by josteink** [dotnet/dotnet-ci#37]
With test-failures now fixed in master, we should try to enable PAL-tests for the coreclr FreeBSD CI-build, to prevent future regressions.

@mmitche Is this something you can handle on your own, or will I need to issue  a PR?

**Comment by mmitche** [comment]
I can handle it

**Comment by josteink** [comment]
Feel free to run a tentative run and if you experience any issues, do give me a shout :)

**Comment by mmitche** [comment]
@josteink Will do

**Comment by josteink** [comment]
If I'm reading the config correctly, the PAL tests are now enabled, and I guess this issue can be closed? :)

https://github.com/dotnet/dotnet-ci/blob/master/jobs/dotnet_coreclr_freebsd_debug/config.xml#L47
https://github.com/dotnet/dotnet-ci/blob/master/jobs/dotnet_coreclr_freebsd_release/config.xml#L47

**Comment by mmitche** [comment]
Yep :)
