### ISSUE TITLE
Enable ARM and AArch64 CI build for CoreCLR

### ISSUE THREAD

**Issue by jasonwilliams200OK** [dotnet/dotnet-ci#49]
With dotnet/coreclr#1292 and dotnet/coreclr#1210 merged, please enable CI build jobs for ARM and AArch64 architectures and add the respective badges in coreclr repo's [README (under Build Status)](https://github.com/dotnet/coreclr/blob/master/README.md#build-status), so others can follow the support status.

@mmitche, @saper

**Comment by mmitche** [comment]
Which platforms was ARM/AArch64 enabled for?  Did appropriate switches get added to the build scripts?

**Comment by jasonwilliams200OK** [comment]
> Which platforms was ARM/AArch64 enabled for?

Linux.

> Did appropriate switches get added to the build scripts?

Yup:

```bash
build.sh arm64
```

```bash
build.sh arm
```

@benpye, @kangroo

**Comment by mmitche** [comment]
@benpye indicated that there is no cross-targeting build available yet, and we don't have arm64 hardware in the lab yet, so I'll need to look into getting that hardware into the lab first.

**Comment by jasonwilliams200OK** [comment]
FTR, I was looking at this piece: https://github.com/dotnet/coreclr/blob/16c43e3/build.sh#L160-L167.

**Comment by benpye** [comment]
@mmitche The arm target obviously doesn't require arm64, but both would be ideal, I will try and get cross compilation working as I said on the other issue.

**Comment by benpye** [comment]
@mmitche For cross compilation we're going to need some rootfs, I think it should be possible to generate ourselves, however (as far as I can tell), it's hard/impossible to do without having root access. Would you rather just package up an Ubuntu 14.04 archive with the libraries we require and host that somewhere, or, generate it on each machine, despite the need for root access at least once to do so. Unless additional dependencies are added we shouldn't need to touch the rootfs after the initial setup.

**Comment by mmitche** [comment]
@benpye Thanks for the info, I'll think on it.

**Comment by mmitche** [comment]
Since all of our Linux images are exactly the same, could we prep once machine with the right rootfs and then deploy it to all of the nodes?

**Comment by benpye** [comment]
Don't see why not, I've written a quick script, should work to generate a rootfs for both arm and arm64, and then if someone wants to cross compile themselves that they can generate it.

**Comment by benpye** [comment]
@mmitche Also another thing that would be nice to have is the ARM mscorlib build, I forgot to add to the usage text, but you can run `build.cmd arm debug linuxmscorlib` and `build.com arm release linuxmscorlib`. We seem to lack an ARM64 target though @kangaroo .

**Comment by kangaroo** [comment]
Yeah I haven't bothered yet with mscorlib.  Its a one line change, but since the JIT isn't ready there isn't a ton of point yet.  I (or someone) needs to do at least HFA first.

**Comment by gitchomik** [comment]
to fix this error:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_arm_linux_debug/1/consoleFull#197657061074b77ed1-74ea-41e6-b970-9241fe4855f3

Please do this: (https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md)

for ARM:
apt-get install binutils-arm-linux-gnueabihf

for ARM64 :
apt-get install binutils-aarch64-linux-gnu

**Comment by shahid-pk** [comment]
@gitchomik  you should probably send in a pull request and tag this issue.

**Comment by mmitche** [comment]
@gitchomik The issue is that I didn't generate the rootfs here.  I'm on it today.

**Comment by gitchomik** [comment]
@mmitche OK, maybe. 
I have got same error but I forgot install binutils (but the rootfs was generated earlier)
