### ISSUE TITLE
Question: Is .NET CLI or VS 2017 supported?

### ISSUE THREAD

**Issue by conniey** [dotnet/dotnet-ci#646]
Hi,

I am trying to update our repository to VS1017, but the build.ps1 uses dotnet.exe and msbuild 15 because we are building a VS2017 extension.  Is the .NET Core CLI 1.0.0 or msbuild 15 supported?  It doesn't appear to be under the [Onboarding Steps](https://github.com/dotnet/dotnet-ci/blob/master/docs/CI-SETUP.md#onboarding-steps-for-your-project), and the [PR is failing](https://ci2.dot.net/job/Microsoft_dotnet-apiport/job/master/job/Debug_prtest/78/console) because it can't locate `dotnet.exe` in its path.

Thanks!

**Comment by mmitche** [comment]
@conniey dotnet.exe will not be on the path on any of the machines. There are simply too many versions laying around to risk putting it on the path.  That said, a machine with VS2017 is available, which should put dotnet.exe on the path if you run the vs developer prompt inside your CI script.

https://github.com/dotnet/dotnet-ci/blob/master/jobs/generation/Utilities.groovy#L239

Let me know if you need help.

**Comment by conniey** [comment]
Thanks!

**Comment by conniey** [comment]
@mmitche, I was checking out my CI build and it appears to be unable to locate Visual Studio 2017.  Could I be missing something?

* [dotnet-apiport PR 411](https://github.com/Microsoft/dotnet-apiport/pull/411/)
   * Script/line it is failing on: [Set-VsDevEnv.ps1 #L45](https://github.com/conniey/dotnet-apiport/blob/eb1a1675cfb74e995a986d7e0385789e7567b3da/build/Set-VsDevEnv.ps1#L31-L45)
* [CI console output](https://ci2.dot.net/job/Microsoft_dotnet-apiport/job/master/job/Debug_prtest/81/console)

Error:
```
11:54:00 D:\j\workspace\Debug_prtestf8d899aa\build\Set-VsDevEnv.ps1 : Could not locate: C:\Program Files (x86)\Microsoft Visual Studio\2017. 
```

**Comment by mmitche** [comment]
@conniey You need to commit the change to the netci.groovy before the PR changes will be visible.

**Comment by conniey** [comment]
@mmitche Hey, I did that and then put my commits on top of it.. but I am getting the same issue. :/  Is there any way to see what's on the machine building the PR?
