### ISSUE TITLE
Consider automating machine setup with Chef or something

### ISSUE THREAD

**Issue by ellismg** [dotnet/dotnet-ci#88]
It may make more sense to move to a model where we have scripts that take a clean machine and install all the required software on the CI machines instead of the model where we do brain surgery on a VM and then capture a new image.

This would make the stuff installed on a machine explicit and we could version it in this repo.

**Comment by ellismg** [comment]
I think if we did it this way we might also be able to force the windows workers to auto-login as part of the setup script.

**Comment by dls314159** [comment]
+1
It's hard to keep documents about that kind of brain surgery up to date.
(e.g. [https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md](https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md))
