### ISSUE TITLE
Getting VS2017 15.5 on CI machines

### ISSUE THREAD

**Issue by conniey** [dotnet/dotnet-ci#905]
We are using dotnet-ci for our gated check-in builds and MicroBuild for our release builds. Unfortunately, MicroBuild has machines on VS2017 15.5 and the latest version available for dotnet-ci is 15.3.

Our release builds are failing because the recommended versions for Microsoft.CodeAnalysis. differ depending on the version of VS installed.

How soon will 15.5 be available? It is blocking our signed release builds. :(

* [Microsoft.CodeAnalysis.FxCopAnalyzers Recommended Versions](https://github.com/dotnet/roslyn-analyzers#recommended-version-of-analyzer-packages)

**Build Exception**
```
CSC:CSC(0,0): Error   CS8032: An instance of analyzer   Microsoft.NetCore.Analyzers.Runtime.TestForNaNCorrectlyAnalyzer cannot be   created from C:\Users\dlab\.nuget\packages\microsoft.netcore.analyzers\2.3.0-beta1\analyzers\dotnet\cs\Microsoft.NetCore.Analyzers.dll   : Exception has been thrown by the target of an invocation..
Process   'msbuild.exe' exited with code '1'.
 
```
/cc: @twsouthwick

**Comment by twsouthwick** [comment]
It would be for Microsoft/dotnet-apiport

**Comment by mmitche** [comment]
@conniey Please use 'latest-dev15-5' for this line https://github.com/Microsoft/dotnet-apiport/blob/dev/netci.groovy#L24

**Comment by davkean** [comment]
This is resolved.
